### ISSUE TITLE
responsibility of commits

### ISSUE THREAD

**Issue by KasperOlesen** [fandul/blog-Entry#1]
Is it possible to blame others for your own mistakes in the code you have comitted to github? Isn't all code tracked so you can see who comitted what, and thereby who broke the app? Is this any different with Jenkins?

**Comment by benthehorn** [comment]
Yes, you can blame whoever you want using git blame!!
Yes ,code is tracked in github, so you can always see who made the mistake. We chose to have Jenkins delete the ready branches, but that's just our implementation. You could leave the commits so that mistakes could be identified, and then use git blame to name and shame!
